---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    new-label: myapp01 
  ports:

  - name: kafkaui 
    protocol: TCP
    port: 9021
    targetPort: 9021
  - name: kafkacon
    protocol: TCP
    port: 8083 
    targetPort: 8083
